Models/Blog.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebsiteMVC.Models
{
     public class MixModel 
     {
          public Posts Posts { get; set; }
          public Comments Comments { get; set; }
          public List<Posts> AllPosts { get; set; } 
          public List<Comments> AllComments { get; set; }
     }

     public class Posts
     {
          [Key]
          public int PostID { get; set; }
          public int CategoryID { get; set; }
          public string PostContent { get; set ; }
          public string PostExcerpt { get; set; }
          public string PostTitle { get; set; }
          public string PostAuthor { get; set; }
          public string PostLocation { get; set; }
          public string PostIP { get; set; }
          public string PostActive { get; set; }
          public bool PostPublished { get; set;  }
          public DateTime PostDate { get; set; }
          public int CommentCount { get; set; }
     }

     public class Comments
     {
          [Key]
          public int CommentID { get; set; }
          public int ParentID { get; set; }
          public string PhotoID { get; set; }
          [Display(Name="Name")]
          public string CommentAuthor { get; set; }
          [Display(Name ="Email")]
          public string CommentAuthorEmail { get; set; }
          [Display(Name ="Website")]
          public string CommentAuthorUrl { get; set; }
          public string CommentAuthorIP { get; set; }
          public DateTime CommentDate { get; set; }
          [Display(Name ="Comment")]
          public string CommentContent { get; set; }
          public string CommentType { get; set; }

     }
}

Areas/Admin/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PersonalWebsiteMVC.Data;
using PersonalWebsiteMVC.Models;
using SolrNet;
using SolrNet.Commands.Parameters;
using SolrNet.Mapping;

namespace PersonalWebsiteMVC.Areas.Admin.Controllers
{
     [Area("Admin")]
     [Authorize(Policy = "Admin")]
     public class BlogController : Controller
     {
          private readonly ApplicationDbContext _db;
          private ISolrOperations<SolrModel> _solr;

          public BlogController(ApplicationDbContext db, ISolrOperations<SolrModel> solr)
          {
               _db = db;
               _solr = solr;
          }

          public IActionResult Index()
          {
               return View(_db.Posts.ToList());
          }

          public IActionResult Create()
          {
               return View();
          }

          [HttpPost]
          public IActionResult OnPostPublish(Posts model)
          {
               if (ModelState.IsValid)
               {
                    var b = new Posts();
                    b.PostContent = model.PostContent;
                    b.PostExcerpt = model.PostExcerpt;
                    b.PostTitle = model.PostTitle;
                    b.CategoryID = model.CategoryID; 
                    b.PostAuthor = model.PostAuthor;
                    b.PostLocation= model.PostLocation;
                    b.PostDate = DateTime.Now;
                    b.PostIP = HttpContext.Connection.RemoteIpAddress.ToString();
                    b.PostActive = "No";
                    _db.Posts.Add(b);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
               }
               return View(model);
          }

          public IActionResult OnPostSaveDraft(Posts model)
          {
               if (ModelState.IsValid)
            {
                    var p = new Posts();
                    
            }
               return View();
          }

          public IActionResult Update(int id)
          {
          
               return View(_db.Posts.Where(b => b.PostID == id).FirstOrDefault());
          }

          [HttpPost]
          public IActionResult Update(int id, Posts model, string Solr)
          {
               if (ModelState.IsValid)
               {
                    var b = _db.Posts.Where(b => b.PostID == id).FirstOrDefault();
                    b.PostContent = model.PostContent;
                    b.PostExcerpt = model.PostExcerpt;
                    b.PostTitle = model.PostTitle;
                    b.PostAuthor = model.PostAuthor;
                    b.PostLocation = model.PostLocation;
                    b.CategoryID = model.CategoryID;
                    _db.Update(b);
                    _db.SaveChanges();
                    if (Solr == "Yes")
                    {
                         var s = new PersonalWebsiteMVC.Models.SolrModel();
                         s.ID = model.PostID.ToString();
                         s.Title = model.PostTitle;
                         s.Url = "http://www.douglasmcgregor.co.uk/Blog?q=" + model.PostID;
                         s.Body = model.PostContent;
                         _solr.Add(s);
                         _solr.Commit();
                    }
                    if (Solr == "No")
                    {
                         SolrQueryByField results = new SolrQueryByField("ID", model.PostID.ToString());
                         _solr.Delete(results.FieldValue);
                         _solr.Commit();
                    }
                    return RedirectToAction("Index");
               }
               return View(model);
          }

          public IActionResult Delete(int id)
          {
               var b = _db.Posts.Where(b => b.PostID == id).FirstOrDefault();
               _db.Remove(b);
               _db.SaveChanges();
               return RedirectToAction("Index");
          }

          public IActionResult Details(int id)
          {
               return View(_db.Posts.Where(b => b.PostID == id).FirstOrDefault());
          }
     }
}

Areas/Admin/Views/Blog/Create.cshtml
@model PersonalWebsiteMVC.Models.Posts
@using PersonalWebsiteMVC.Data
@inject ApplicationDbContext db
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Shared/_Layout.cshtml";
}

<h1 class="bg-info text-white">Create</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>
<div asp-validation-summary="All" class="text-danger"></div>

<form method="post">

    <div class="form-group form-row">
        <label asp-for="PostContent">Content:</label>
        <textarea asp-for="PostContent" id="ckeditor1"></textarea>
    </div>
    <div class="form-group form-row">
        <label asp-for="PostTitle">Title:</label>
        <input asp-for="PostTitle" />
    </div>
    <div class="form-group form-row">
        <label asp-for="CategoryID">Category:</label>
        <select asp-for="CategoryID">
            @foreach (var item in db.Categories)
            {
                <option value="@item.CategoryID" />
                @item.Category
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary" asp-page-handler="PublishPost">Publish</button>
    <button type="submit" class="btn btn-secondary" asp-page-handler="SaveDraft">Save Draft</button>

</form>

Areas/Admin/Views/Blog/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

Areas/Admin/Views/Blog/Details.cshtml
@model PersonalWebsiteMVC.Models.Posts

@{
     ViewData["Title"] = "Details";
     Layout = "~/Areas/Admin/Shared/_Layout.cshtml";
}

<h1 class="bg-info text-white p-1">Details</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>


<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.CategoryID)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.CategoryID)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostContent)
</dt>
<dd class="col-sm-10">
     @Html.Raw(Html.DisplayFor(model => model.PostContent))
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostTitle)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostTitle)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostAuthor)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostAuthor)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostLocation)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostLocation)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostIP)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostIP)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostActive)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostActive)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.PostDate)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.PostDate)
</dd>
<dt class="col-sm-2">
     @Html.DisplayNameFor(model => model.CommentCount)
</dt>
<dd class="col-sm-10">
     @Html.DisplayFor(model => model.CommentCount)
</dd>
    </dl>

Areas/Admin/Views/Blog/Index.cshtml
@model IEnumerable<Posts>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Shared/_Layout.cshtml";
}

<h1 class="bg-info text-white">Blog</h1>
<a asp-action="Create" class="btn btn-secondary">Create</a>

<table class="table text-center">
     <thead class="font-weight-bold"><td>ID</td><td>Title</td><td>User</td><td>Update</td><td>Details</td><td>Delete</td></thead>
     @foreach (var item in Model)
     {
          <tr>
          <td>@item.PostID</td>
          <td>@item.PostTitle</td>
          <td>@item.PostAuthor</td>
          <td><a asp-action="Update" class="btn btn-primary" asp-route-id="@item.PostID">Update</a></td>
          <td><a asp-action="Details" class="btn btn-primary" asp-route-id="@item.PostID">Details</a></td>
          <td><a asp-action="Delete" class="btn btn-primary" asp-route-id="@item.PostID">Delete</a></td>
          </tr>
     }
</table>

Areas/Admin/Views/Blog/Update.cshtml
@model Posts
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Shared/_Layout.cshtml";
}

@using PersonalWebsiteMVC.Data
@inject ApplicationDbContext db

<h1 class="bg-info text-white">Update</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="PostContent">Content:</label>
        <textarea asp-for="PostContent" id="ckeditor1"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="PostTitle">Title:</label>
        <input asp-for="PostTitle" />
    </div>
    <div class="form-group">
        <label asp-for="PostLocation">Location:</label>
        <input asp-for="PostLocation" id="searchTextField" />
    </div>
     <div class="form-group">
          <label asp-for="CategoryID">Category</label>
          <select asp-for="CategoryID">
                @foreach (var item in db.Categories)
                {
                     <option value="@item.CategoryID">@item.Category</option>
                }
          </select>
     </div>
    <div class="form-group">
          <label>Add to Solr</label>
            <select name="Solr">
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
            <input type="hidden" name="postID" asp-for="PostID" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&key=AIzaSyBLgq2BcCrbNfFlvviKbpOvAikzKMlPYp4"></script>
<script>function initialize() {
        var input = document.getElementById("searchTextField");
        new google.maps.places.Autocomplete(input);
    }

    google.maps.event.addDomListener(window, "load", initialize);
</script>